### ISSUE TITLE
Upgrade to Capacitor 2

### ISSUE THREAD

**Issue by RoopeHakulinen** [go-u/capacitor-keep-screen-on#2]
Currently registering the plugin with Capacitor 2 causes the following error:
```
ERROR in src/app/app.component.ts:110:23 - error TS2345: Argument of type 'CapacitorKeepScreenOnWeb' is not assignable to parameter of type 'WebPlugin'.
Property 'removeAllListeners' is missing in type 'CapacitorKeepScreenOnWeb' but required in type 'WebPlugin'.
    
    110     registerWebPlugin(new CapacitorKeepScreenOnWeb());
```

which can be circumvented by disabling typing with:

```
registerWebPlugin(new (CapacitorKeepScreenOnWeb as any)());
```

The cause is obviously the changed typing for `WebPlugin` interface of Capacitor core.

**Comment by RoopeHakulinen** [comment]
I raised [a PR](https://github.com/go-u/capacitor-keep-screen-on/pull/3) to update the dependency itself. 

I think it might also be a good idea to use `peerDependencies` over `dependencies` to allow users of this plugin to control the version of Capacitor instead of the plugin installing the old version of as transitive dependency like now.

Anyways, thanks for all the work put into this. Helps a lot :)

**Comment by go-u** [comment]
Thanks a lot. I merged your pull request :)

About peerDependencies, I'll update it and release a new version to NPM.

**Comment by go-u** [comment]
v0.0.4 released :confetti_ball:

If you find a bug related to the update, please report it.
I'll leave this issue open for 1-2 weeks. Thanks :)

**Comment by RoopeHakulinen** [comment]
Awesome - thanks for fixing it so fast! Works great in my app now. I'll re-open/issue a new bug if there are any problems. I wouldn't expect any issues as I've already been using Capacitor 2 since its release with the typing disabled for this one.
