### ISSUE TITLE
Not working with Android X

### ISSUE THREAD

**Issue by RoopeHakulinen** [go-u/capacitor-keep-screen-on#6]
As part of Android X the support library [was removed](https://developer.android.com/topic/libraries/support-library) in favor of the Android X libraries. The earlier used reference to that old library causes app to crash on startup for missing dependency. 

It would be awesome to release a version like 1.0.0-alpha.1 to verify everything works still great. I guess it needs to be a major version so that this won't break any existing apps since it now requires at least the SDK level 28 (Android X).

**Comment by RoopeHakulinen** [comment]
Opened #5 for this.

**Comment by go-u** [comment]
Thanks!

I'll do the following in a few days.
If you have any suggestions, please let me know :)

- Update demo app to Android X for future test
  (SPA part is [here](https://github.com/go-u/capacitor-keep-screen-on/tree/master/demo) and Android part is [here](https://github.com/go-u/capacitor-keep-screen-on/tree/master/demo/src-capacitor/android))
- Test your pull request #5 with demo app, and merge it
- Release new version like **v1.0.0-alpha.1** or **v1.0.0**

**Comment by RoopeHakulinen** [comment]
Awesome. I'm waiting eagerly for a test version as I cannot compile my app for distribution before this has been resolved so just let me know as soon as there's anything to test :)

**Comment by go-u** [comment]
Hi, @RoopeHakulinen 

I did above things  🎉 
Now, we can use "capacitor-keep-screen-on@1.0.0-alpha.1" from NPM.

If you find a bug, please report it.
Thanks 😄

**Comment by RoopeHakulinen** [comment]
Thanks a lot! I'll test it through today :)

**Comment by RoopeHakulinen** [comment]
I'm running into the same problem with the dependencies as before. Looks like they are still not peerDependencies so I get the same problem as earlier where the WebPlugin has changed its API and as such the plugin cannot be registered but with Capacitor versions 2.1.0 vs 2.0.0 this time. 

![image](https://user-images.githubusercontent.com/2197974/81469848-04630c00-91f0-11ea-8c28-b43f8a0262bf.png)

![image](https://user-images.githubusercontent.com/2197974/81469893-5efc6800-91f0-11ea-9736-f71f356deb09.png)

**Comment by go-u** [comment]
Thanks your report ! :smile: 

The current "package.json" is this.
https://github.com/go-u/capacitor-keep-screen-on/blob/95a4b4ee85e6d797e08407bad3d00e4222bb4bdc/package.json#L15-L19

Mmm.., These lines looks good. Or, Am I making a mistake? :thinking: 

If you can, try `"rm -rf node_modules"` and re-install packages ?

**Comment by RoopeHakulinen** [comment]
That is indeed what I did and still this problem occurs. Also, npm is showing them as dependencies as shown in the other image I posted. Yet, the package.json looks right to me so there must be something else. Let me google for a while.

For reference, here's [a package](https://www.npmjs.com/package/@ngx-translate/core) called `@ngx-translate/core` for which the [package.json](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/package.json) contains `peerDependencies` and if you look at it in npm it looks like this:

![image](https://user-images.githubusercontent.com/2197974/81470704-e5b34400-91f4-11ea-86cf-94a944e11216.png)

**Comment by RoopeHakulinen** [comment]
Oh and good news. Everything works great other than for this typing issue so thanks for that! :)

**Comment by RoopeHakulinen** [comment]
So to investigate this further, here's what I found and think has happened. 

Having a look at the library code npm installs on my machine, I can see that the package.json has two sets of dependencies (normal and peer):

![image](https://user-images.githubusercontent.com/2197974/81471167-edc0b300-91f7-11ea-99cb-2bf23d5d0bfd.png)

This is caused probably by the fact that during the dev you needed the actual dependencies and as such installed them. Now, npm doesn't know anything about git and what is the status of the files there, right? Instead it uses just what you have locally when publishing to its registry. So at the moment of time when you run the `npm publish` your `package.json` probably contained still this stuff. Could this be the case maybe?

**Comment by go-u** [comment]
Hi, @RoopeHakulinen 😄 

I found the cause thanks to your report! 🎉 
The cause was in the Github Actions code used for the "build" and "npm publish" of the package.

I need a capacitor to build the package, but I solved this by installing it with the --no-save option.

Thank you for reporting patiently. 📝 
I am not certain that this has solved all the problems, so if you find any problems please let me know. (You don't have to hurry to test it. I'll leave this issue open for 1-2 weeks.)

https://github.com/go-u/capacitor-keep-screen-on/blob/0f3b2de20e4bae5fbe202d6046e56267a45e4a29/.github/workflows/publish.yml#L17

**Comment by RoopeHakulinen** [comment]
Everything works great now. Awesome stuff! 

Peer dependencies can be rather annoying and the developer experience is far from ideal. Anyways, good that you got it working and all is now working great for me! Maybe worth just adding something on the README about versioning like a version matrix: 

![image](https://user-images.githubusercontent.com/2197974/81476593-54a39380-921b-11ea-9371-ac9a9e81f99e.png)

Thanks a lot for all the work you put into this!
